global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#anton_cherenkov'
 
