version: '3.4'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
 
  ui:
    image: ${USER_NAME}/ui
    ports:
      - 9292:9292/tcp
    networks:
      - front_net
 
  post:
    image: ${USER_NAME}/post
    networks:
      - front_net
      - back_net
 
  comment:
    image: ${USER_NAME}/comment
    networks:
      - front_net
      - back_net
 
volumes:
  post_db:
  prometheus_data:
 
networks:
  front_net:
  back_net:
 
