version: '3.4'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
 
  ui:
    image: ${USERNAME}/ui
    ports:
      - 9292:9292/tcp
    networks:
      - front_net
 
  post:
    image: ${USERNAME}/post
    networks:
      - front_net
      - back_net
 
  comment:
    image: ${USERNAME}/comment
    networks:
      - front_net
      - back_net
 
volumes:
  post_db:
  prometheus_data:
 
networks:
  front_net:
  back_net:
 
